Version 1.4.0-rc release
docusign/docusign-admin-php-client pull request #8
Opened 2023-08-03 23:52 UTC by InbarGazit

### Changed
- Added support for version v2.1-1.3.0 of the DocuSign Admin API.
- Updated the SDK release version.

New endpoints:
* `GET /v1/organizations/{organizationId}/assetGroups/accounts` Get asset group accounts for an organization.
* `POST /v1/organizations/{organizationId}/assetGroups/accountClone` Clone an existing DocuSign account.
* `GET /v1/organizations/{organizationId}/assetGroups/accountClones` Gets all asset group account clones for an organization.
* `GET /v1/organizations/{organizationId}/assetGroups/{assetGroupId}/accountClones/{assetGroupWorkId}` Gets information about a single cloned account.

2023-08-04 17:18 UTC, AaronWDS requested changes
#[\ReturnTypeWillChange] is a php8.1 attribute but we're referencing that this is php 7.4 combatible code. I suggest to reflect PHP compatility in the changelog and readme files

2023-08-04 17:18 UTC, AaronWDS commented on src/Model/AssetGroupAccountCloneSourceAccount.php
> +    #[\ReturnTypeWillChange]
this is a php 8.1 feature

2023-08-09 01:24 UTC, dbbrahmbhatt approved these changes

2023-08-09 01:27 UTC, AaronWDS approved these changes

2023-08-09 01:36 UTC, merged